    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        try_files $uri /index.html;
    }

    location /reserva {
        proxy_pass http://backend;
    }

    location /factura {
        proxy_pass http://backend;
        client_max_body_size 10m;
    }

    location /cliente {
        proxy_pass http://backend;
    }

    location /loginuser {
        proxy_pass http://backend;
    }

    location /upload-booking {
        proxy_pass http://backend;
    }

    location /booking-sync {
        proxy_pass http://backend;
    }

    location /menu {
        proxy_pass http://backend;
    }

    location /precios-base {
        proxy_pass http://backend;
    }

    location /precios-booking {
        proxy_pass http://backend;
    }

    location /usuarios {
        proxy_pass http://backend;
    }

    location /proveedores {
        proxy_pass http://backend;
    }

    location /movimientos-banco {
        proxy_pass http://backend;
    }

    location /parse-dni {
        proxy_pass http://backend;
        client_max_body_size 10m;
    }

    location /checkin-preview {
        proxy_pass http://backend;
    }

    location /checkin-xml {
        proxy_pass http://backend;
    }

    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
    }
